"""Small interfaces shared by deployment transactions."""

from collections.abc import Callable
from typing import Protocol


class ManagerService(Protocol):
    def daemon_reload(self) -> None: ...

    def enable(self) -> None: ...

    def disable(self) -> None: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def restart(self) -> None: ...

    def is_active(self) -> bool: ...

    def is_enabled(self) -> bool: ...

    def sanitized_status(self) -> tuple[str | None, str | None, str | None]: ...


HealthVerifier = Callable[[str, int], None]
